---
abstract: 'Quickly show available class methods and documentation.'
author:
  - 'Tim Potapov <tim.potapov[AT]gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Pod
provides:
  App::Pod:
    file: lib/App/Pod.pm
    version: '0.05'
requires:
  Module::Functions: v2.1.3
  Mojolicious: '9.19'
  Pod::Query: '0.13'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
